version: '3.8'
services:
  postgres: 
    image : postgres
    restart: always
    container_name: hexagonaldb
    hostname: host-postgres
    ports:
     - '5432:5432'
    environment:
      - POSTGRES_USER=leowader
      - POSTGRES_PASSWORD=leowaderhe
      - POSTGRES_DB=hexagonal
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: